#############################################################################
# Makefile for building: Mixer
# Generated by qmake (2.01a) (Qt 4.8.4) on: Fri Nov 1 12:07:40 2013
# Project:  Mixer.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Mixer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		test.cpp \
		capture.cpp \
		buffer.cpp \
		preview.cpp \
		fader.cpp \
		save.cpp moc_mainwindow.cpp \
		moc_test.cpp \
		moc_capture.cpp \
		moc_preview.cpp \
		moc_fader.cpp
OBJECTS       = main.o \
		mainwindow.o \
		test.o \
		capture.o \
		buffer.o \
		preview.o \
		fader.o \
		save.o \
		moc_mainwindow.o \
		moc_test.o \
		moc_capture.o \
		moc_preview.o \
		moc_fader.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Mixer.pro
QMAKE_TARGET  = Mixer
DESTDIR       = 
TARGET        = Mixer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_input.h ui_test.h ui_capture.h ui_preview.h ui_fader.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Mixer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Mixer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Mixer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Mixer1.0.0 || $(MKDIR) .tmp/Mixer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Mixer1.0.0/ && $(COPY_FILE) --parents mainwindow.h test.h capture.h buffer.h preview.h fader.h save.h .tmp/Mixer1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp test.cpp capture.cpp buffer.cpp preview.cpp fader.cpp save.cpp .tmp/Mixer1.0.0/ && $(COPY_FILE) --parents mainwindow.ui input.ui test.ui capture.ui preview.ui fader.ui .tmp/Mixer1.0.0/ && (cd `dirname .tmp/Mixer1.0.0` && $(TAR) Mixer1.0.0.tar Mixer1.0.0 && $(COMPRESS) Mixer1.0.0.tar) && $(MOVE) `dirname .tmp/Mixer1.0.0`/Mixer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Mixer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_test.cpp moc_capture.cpp moc_preview.cpp moc_fader.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_test.cpp moc_capture.cpp moc_preview.cpp moc_fader.cpp
moc_mainwindow.cpp: capture.h \
		preview.h \
		buffer.h \
		fader.h \
		test.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_test.cpp: test.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) test.h -o moc_test.cpp

moc_capture.cpp: preview.h \
		buffer.h \
		capture.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) capture.h -o moc_capture.cpp

moc_preview.cpp: buffer.h \
		preview.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) preview.h -o moc_preview.cpp

moc_fader.cpp: buffer.h \
		fader.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) fader.h -o moc_fader.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_input.h ui_test.h ui_capture.h ui_preview.h ui_fader.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_input.h ui_test.h ui_capture.h ui_preview.h ui_fader.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_input.h: input.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic input.ui -o ui_input.h

ui_test.h: test.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic test.ui -o ui_test.h

ui_capture.h: capture.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic capture.ui -o ui_capture.h

ui_preview.h: preview.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic preview.ui -o ui_preview.h

ui_fader.h: fader.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic fader.ui -o ui_fader.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		capture.h \
		preview.h \
		buffer.h \
		fader.h \
		test.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		capture.h \
		preview.h \
		buffer.h \
		fader.h \
		test.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

test.o: test.cpp test.h \
		ui_test.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o test.cpp

capture.o: capture.cpp capture.h \
		preview.h \
		buffer.h \
		ui_capture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o capture.o capture.cpp

buffer.o: buffer.cpp buffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buffer.o buffer.cpp

preview.o: preview.cpp preview.h \
		buffer.h \
		ui_preview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preview.o preview.cpp

fader.o: fader.cpp fader.h \
		buffer.h \
		ui_fader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fader.o fader.cpp

save.o: save.cpp save.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o save.o save.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_test.o: moc_test.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_test.o moc_test.cpp

moc_capture.o: moc_capture.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_capture.o moc_capture.cpp

moc_preview.o: moc_preview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preview.o moc_preview.cpp

moc_fader.o: moc_fader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fader.o moc_fader.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

